# Generated by Django 4.1.7 on 2023-08-01 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'tarea', 'verbose_name_plural': 'tareas'},
        ),
    ]
