# Generated by Django 4.1.7 on 2023-08-01 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_alter_task_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUserApp',
            new_name='CustomerUser',
        ),
    ]
