# Generated by Django 4.1.7 on 2023-08-02 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_customuserapp_customeruser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'etiqueta', 'verbose_name_plural': 'etiquetas'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='categories',
            new_name='tag',
        ),
    ]
